--- 
:ask_for_from: true
:ask_for_to: true
:ask_for_subject: true
:confirm_no_attachments: true
:confirm_top_posting: true
:discard_snippets_from_encrypted_messages: false
:edit_signature: true
:editor: vim -f +'set ft=mail' +'set tw=72' +'set nohlsearch' +'/^\s*$'
:thread_by_subject: false
#:wrap_width: 76

:default_attachment_save_dir: ~/Dropbox/tmp

:accounts: 
  :default: 
    :sendmail: msmtp --read-envelope-from -t
    :email: vallentin@icir.org
    :name: Matthias Vallentin
  :private: 
    :sendmail: msmtp --read-envelope-from -t --account=eecs 
    :email: matthias@vallentin.net
    :name: Matthias Vallentin
    :alternates:
    - m@vallentin.net
    - maddi@vallentin.net
  :ucb: 
    :sendmail: msmtp --read-envelope-from -t --account=cal
    :email: vallentin@berkeley.edu
    :name: Matthias Vallentin
    :alternates:
    - mpm@berkeley.edu
    - mavam@berkeley.edu
  :eecs: 
    :sendmail: msmtp --read-envelope-from -t --account=eecs
    :email: vallentin@cs.berkeley.edu
    :name: Matthias Vallentin
    :alternates:
    - vallentin@eecs.berkeley.edu
    - mv@cs.berkeley.edu
    - mv@eecs.berkeley.edu
    - mavam@cs.berkeley.edu
    - mavam@eecs.berkeley.edu
    - matthias.vallentin@cs.berkeley.edu
    - matthias.vallentin@eecs.berkeley.edu
  :icsi: 
    :sendmail: msmtp --read-envelope-from -t --account=eecs
    :email: vallentin@icsi.berkeley.edu
    :name: Matthias Vallentin
    :alternates:
    - vallenti@icsi.berkeley.edu
    - mvallentin@lbl.gov
